### ISSUE TITLE
How to ouput Info/Warning/Debug/Error/Notify log content to the log file?

### ISSUE THREAD

**Issue by KISSMonX** [gogf/gf#1525]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.5 windows/amd64

### 2. What version of `GoFrame` are you using?

gf 1.16.6

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

Like below config file:

`level = "all" `

```toml
# 全局日志配置
[logger]
	path                 = "log/HLTAM"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
	file                 = "{Y-m-d}.log"    # 日志文件格式。默认为"{Y-m-d}.log"
	prefix               = ""               # 日志内容输出前缀。默认为空
	level                = "all"            # 日志输出级别
	ctxKeys              = []               # Context上下文变量名称，自动打印Context的变量到日志中。默认为空
	headerPrint          = true             # 是否打印日志的头信息。默认true
	stdoutPrint          = true             # 日志是否同时输出到终端。默认true
	rotateSize           = "1M"             # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
	rotateBackupLimit    = 1024               # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
	rotateBackupExpire   = "365d"           # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
	rotateBackupCompress = 0                # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
	rotateCheckInterval  = "1h"             # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时
	writerColorEnable    = false            # 日志文件是否带上颜色。默认false，表示不带颜色
```

### 5. What did you expect to see?

`level = "all" `

I want the os/glog output INFO/DEBUG/WARNING/ERROR/PANIC to log file.
Like the StdOutput display.

![image](https://user-images.githubusercontent.com/2876745/146702601-fc1d2d6f-e3cf-4024-a994-ca0cb05d36ec.png)

### 6. What did you see instead?

But, the server.log just have gf log, not the user define Info/Warning/Debug/Error log content.

```log
2021-12-20 10:17:26.067 51712: http server started listening on [:9736] 

  SERVER  | DOMAIN  | ADDRESS | METHOD |             ROUTE             |                             HANDLER                             | MIDDLEWARE  
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | PUT    | /v1/cabinet/alert/new         | HLTAMServer/app/api/device.(*CabinetAPI).AlertNew-fm            |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/cabinet/alert/records     | HLTAMServer/app/api/device.(*CabinetAPI).AlertRecords-fm        |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/cabinet/all/latest        | HLTAMServer/app/api/device.(*CabinetAPI).AllDeviceLatestData-fm |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/cabinet/data              | HLTAMServer/app/api/device.(*CabinetAPI).Data-fm                |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | PUT    | /v1/cabinet/data              | HLTAMServer/app/api/device.(*CabinetAPI).AddData-fm             |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | DELETE | /v1/cabinet/delete            | HLTAMServer/app/api/device.(*CabinetAPI).Delete-fm              |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/cabinet/info              | HLTAMServer/app/api/device.(*CabinetAPI).Info-fm                |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | POST   | /v1/cabinet/interval          | HLTAMServer/app/api/device.(*CabinetAPI).SetInterval-fm         |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/cabinet/list              | HLTAMServer/app/api/device.(*CabinetAPI).List-fm                |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | PUT    | /v1/cabinet/new               | HLTAMServer/app/api/device.(*CabinetAPI).New-fm                 |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | PUT    | /v1/cabinet/operation/new     | HLTAMServer/app/api/device.(*CabinetAPI).OperationNew-fm        |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/cabinet/operation/records | HLTAMServer/app/api/device.(*CabinetAPI).OperationRecords-fm    |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | POST   | /v1/cabinet/state             | HLTAMServer/app/api/device.(*CabinetAPI).SetState-fm            |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | POST   | /v1/cabinet/threshold         | HLTAMServer/app/api/device.(*CabinetAPI).SetThreshold-fm        |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | GET    | /v1/hello                     | HLTAMServer/app/api.(*HelloAPI).Index-fm                        |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | POST   | /v1/ns/error                  | HLTAMServer/app/api/device.(*NSServerAPI).Error-fm              |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | POST   | /v1/ns/join                   | HLTAMServer/app/api/device.(*NSServerAPI).Join-fm               |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
  default | default | :9736   | POST   | /v1/ns/uplink                 | HLTAMServer/app/api/device.(*NSServerAPI).Uplink-fm             |             
----------|---------|---------|--------|-------------------------------|-----------------------------------------------------------------|-------------
 

```

**Comment by KISSMonX** [comment]
anyone here?

**Comment by KISSMonX** [comment]
https://goframe.org/pages/viewpage.action?pageId=1114174

```toml
[server]
	LogPath           = "/var/log/gf-demos/server"
    LogStdout         = false
    ErrorStack        = true
    ErrorLogEnabled   = true
    ErrorLogPattern   = "error.{Ymd}.log"
    AccessLogEnabled  = true
    AccessLogPattern  = "access.{Ymd}.log"

```
