### ISSUE TITLE
2.1版本gf build命令没有进行pack打包

### ISSUE THREAD

**Issue by demozx** [gogf/gf#1971]
2.1版本gf build命令没有进行pack打包

（1）gf build没有自动执行pack
（2）手动pack文件到internal/packed/data.go，然后执行gf build，将编译后的可执行文件在同环境的新设备运行，结果无法运行，原因是manifest和resource的文件找不到。

config.yaml配置如下

```
gfcli:
  build:
    name: "gfCms"
    arch: "amd64"
    system: "linux"
    mod: "none"
    cgo: 0
    pack: "manifest/config,manifest/i18n,resource/public,resource/template"
    version: ""
    output: "./bin"
    extra: ""
```

**Comment by stevenyangecho** [comment]
同问,项目没办法继续了...

**Comment by demozx** [comment]
看了下源码，原pack应改为如下两个配置，这样可以pack了，本地直接run的话，确实是读取的build_pack_data.go文件，但是build后的二进制文件运行仍然是找不到文件。

```
gfcli:
  build:
    packSrc: "manifest/config,resource/public,resource/template,resource/i18n"
    packDst: "internal/packed/build_pack_data.go"
```

**Comment by XiaobinZhao** [comment]
@demozx  按照你的配置，并没有生效呢
```
GoFrame CLI Tool v2.1.4, https://goframe.org
GoFrame Version: v2.1.4 in current go.mod
CLI Installed At: /usr/local/sbin/gf
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.1.4
  Git Commit:  2022-08-26 15:45:41 a0619f7ff0e1d7766884e3062d1b3b0947c87da4
  Build Time:  2022-08-26 15:51:38
```
setting.toml配置文件如下
```
[gfcli]
    [gfcli.build]
        name=      "csdp-mgr"
        path=      "./bin"
        arch=      "amd64"
        system=    "linux"
        mod=       "none"
        cgo=       0
        packSrc=   "manifest/config,resource/i18n,resource/public"
        packDst=   "internal/packed/build_pack_data.go"
        version=   ""
        output=    ""
        extra=     ""
```
执行gf build 打包成功之后，把二进制文件放到另一个环境中执行报错：
```
root@xview:~# ./csdp-mgr
2022-09-20 18:16:34.903 [FATA] SetServerRoot failed: cannot find "/resource/public" in following paths:
1. /root
1. cannot find "/resource/public" in following paths:
1. /root
   1).  github.com/gogf/gf/v2/os/gfile.Search
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gfile/gfile_search.go:55
   2).  github.com/gogf/gf/v2/net/ghttp.(*Server).SetServerRoot
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/net/ghttp/ghttp_server_config_static.go:57
   3).  github.com/gogf/gf/v2/net/ghttp.(*Server).SetConfig
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/net/ghttp/ghttp_server_config.go:355
   4).  github.com/gogf/gf/v2/net/ghttp.(*Server).SetConfigWithMap
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/net/ghttp/ghttp_server_config.go:336
   5).  github.com/gogf/gf/v2/frame/gins.Server.func1
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/frame/gins/gins_server.go:70
   6).  github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/container/gmap/gmap_hash_str_any_map.go:216
   7).  github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/container/gmap/gmap_hash_str_any_map.go:253
   8).  github.com/gogf/gf/v2/frame/gins.Server
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/frame/gins/gins_server.go:37
   9).  github.com/gogf/gf/v2/frame/g.Server
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/frame/g/g_object.go:32
   10). csdp-mgr/internal/cmd.glob..func1
    	/mnt/e/go-workspace/host-agent/csdp-mgr/internal/cmd/cmd.go:25
   11). github.com/gogf/gf/v2/os/gcmd.(*Command).doRun
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:148
   12). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:81
   13). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:40
   14). github.com/gogf/gf/v2/os/gcmd.(*Command).Run
    	/root/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:34
   15). main.main
    	/mnt/e/go-workspace/host-agent/csdp-mgr/main.go:12
```

我姿势不对么?

**Comment by demozx** [comment]
@XiaobinZhao 确实有问题，resource/public无法被打包，可能是resource/public作为serverRoot的原因，继续等大佬修复吧

**Comment by gqcn** [comment]
@stevenyangecho @XiaobinZhao @demozx 我看看呢。

**Comment by gqcn** [comment]
@stevenyangecho @XiaobinZhao @demozx 不好意思各位，我check了一下，从某个版本开始，参数名称有调整，给大家一个示例的配置：
```yaml
gfcli:
  # 工具编译配置
  build:
    name:     "focus"
    arch:     "amd64"
    system:   "darwin"
    packSrc:  "resource,manifest"
    mod:      ""
    cgo:      0
```

![image](https://user-images.githubusercontent.com/26347176/195112561-c3397d73-72cd-4b15-be0c-1ee536b040ea.png)

大家可以在代码中通过`gres.Dump()`方法查看打包的内存文件，我是这么来调试的：
![image](https://user-images.githubusercontent.com/26347176/195112822-8ef7a4cf-85a1-48b3-b1f1-2325abe350b2.png)
运行后，像这样的，这些文件都能被程序自动识别到，配置路径和开发时一样，程序代码不需要做额外设置：
![image](https://user-images.githubusercontent.com/26347176/195112941-e9d061c8-c372-468d-8c4b-215bf9627fc2.png)
