### ISSUE TITLE
gf-cli 2.1.1 gf gen dao提示配置找不到database节点

### ISSUE THREAD

**Issue by sersoong** [gogf/gf#1984]
### 1. What version of `Go` and system type/arch are you using?
go 1.17.11 windows

### 2. What version of `GoFrame` are you using?
v2.0.6

### 3. Can this issue be re-produced with the latest release?
是

### 4. What did you do?
配置好manifest/config/config.yaml中的gfcli.gen.dao和database节点，运行gf gen dao
```yaml
server:
  address:     ":8099"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(10.168.150.254:3308)/auth"
      tables: ""
      group: "auth"
      jsonCase: "CamelLower"
      prefix: "auth_"

database:
  auth:
    type:  "mysql"
    link:  "root:123456@tcp(10.168.150.254:3308)/auth"
    prefix: "auth_"
    debug: true
```
报错：
```
2022-07-08 16:58:57.410 [FATA] {84c3c77ff4ceff16d2f26c37aaba8ab4} database initialization failed: configuration missing for database node "database"
1. database initialization failed: configuration missing for database node "database"
   1).  github.com/gogf/gf/v2/frame/gins.Database.func1
        /home/runner/work/gf/gf/frame/gins/gins_database.go:67
   2).  github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck
        /home/runner/work/gf/gf/container/gmap/gmap_hash_str_any_map.go:216
   3).  github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock
   4).  github.com/gogf/gf/v2/frame/gins.Database
        /home/runner/work/gf/gf/frame/gins/gins_database.go:39
   5).  github.com/gogf/gf/v2/frame/g.DB
        /home/runner/work/gf/gf/frame/g/g_object.go:87
   6).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.doGenDaoForArray
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:244
   7).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.cGenDao.Dao
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:182
   8).  github.com/gogf/gf/v2/os/gcmd.newCommandFromMethod.func1
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_object.go:315
   9).  github.com/gogf/gf/v2/os/gcmd.(*Command).doRun
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:151
   10). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:90
   11). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:40
   12). github.com/gogf/gf/v2/os/gcmd.(*Command).Run
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:34
   13). main.main
        /home/runner/work/gf/gf/cmd/gf/main.go:69
```

### 5. What did you expect to see?
gf gen dao能正常工作
