### ISSUE TITLE
数据库日志设置并没有使用全局logger设置

### ISSUE THREAD

**Issue by qq413434162** [gogf/gf#2134]
在框架启动之前的,添加了gcron任务,而任务中数据库执行日志记录并没有使用全局logger设置

框架版本:
GoFrame CLI Tool v2.1.4, https://goframe.org
GoFrame Version: v2.1.4 in current go.mod

代码如下:

```go
s   = g.Server()
_, _ = gcron.AddSingleton(ctx, "0 */1 * * * *", a, "a")
s.Run()

func a(ctx context.Context) {
// 执行一系列数据库操作
}
```

1.我是如何发现?

框架配置
```yaml

server:
    LogPath:          "/log/go/"
    LogStdout:        false
    ErrorStack:       true
    ErrorLogEnabled:  true
    ErrorLogPattern:  "error-{Ymd}.log"
    AccessLogEnabled: true
    AccessLogPattern: "access-{Ymd}.log"

logger:
    Path:    "/log/go/"
    File:    "a.log"
    RotateSize: "100M"
    RotateBackupLimit:     50
    RotateBackupCompress:  9
    Level : "all"
    Stdout: false

database:
    default:
        -  link: "...省略"
           debug: true
```

无法在a.log找到数据库执行的debug日志,却在/log/go/{Y-m-g}.log日志中看到

注意:
/log/go/{Y-m-g}.log我理解是stdout输出

2.我是如何使用其他方法也能写到a.log

经过修改的框架配置
```yaml
database:
    logger:
        Path:    "/log/go/"
        File:    "a.log"
        Level : "all"
        Stdout: false
    default:
        -  link: "...省略"
           debug: true
```

3.我的疑问
3.1 是否 gcron.AddSingleton 在框架启动之前添加的,导致还没有加载全局日志到gdb中?
3.2 我这样实现有无问题?
3.3 还有无其他办法实现?
