### ISSUE TITLE
Cannot startup when enable RotateSize or RotateExpire

### ISSUE THREAD

**Issue by doyard** [gogf/gf#2152]
### 1. What version of `Go` and system type/arch are you using?

go.1.18.3

### 2. What version of `GoFrame` are you using?

v2.1.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

```yaml
server:
      address: ":8080"
      openapiPath: "/api.json"
      swaggerPath: "/swagger"
      logPath: "/var/www/logs"    
      logStdout: true 
      errorStack: true 
      errorLogEnabled: true 
      errorLogPattern: "error-{Ymd}.log"
      accessLogEnabled: true 
      accessLogPattern: "access-{Ymd}.log" 
      logger:
        path: "/var/www/logs" 
        file: "{Y-m-d}.log"    
        level: "info" 
        stdout: true 
        rotateSize: 100
        rotateExpire: "24h"  
        rotateBackupLimit: 10  
        rotateBackupExpire: "60d" 
        rotateBackupCompress: 9  
        rotateCheckInterval: "1h"
```
Error lines
```go
// It just initializes once for each logger.
	if p.config.RotateSize > 0 || p.config.RotateExpire > 0 {
                # The mem addr has beed changed and p.init is nil
		if !p.init.Val() && p.init.Cas(false, true) {
			gtimer.AddOnce(context.Background(), p.config.RotateCheckInterval, p.rotateChecksTimely)
			intlog.Printf(ctx, "logger rotation initialized: every %s", p.config.RotateCheckInterval.String())
		}
	}
```
how run the server
```go
func main() {
	s := g.Server()
	s.BindHandler("/metrics", func(r *ghttp.Request) {
		promhttp.Handler().ServeHTTP(r.Response.Writer, r.Request)
	})
	s.BindHandler("/health", func(r *ghttp.Request) {
		r.Response.WriteJson(g.Map{"status": "UP"})
	})
	cmd.Main.Run(gctx.New())
}
```

### 5. What did you expect to see?
Startup successfully

### 6. What did you see instead?
```bash
2022-09-26 17:06:03.794 [FATA] {a85319648b5d18179da2051136f0a84b} exception recovered: runtime error: invalid memory address or nil pointer dereference
1. exception recovered: runtime error: invalid memory address or nil pointer dereference
   1).  github.com/gogf/gf/v2/os/gcmd.(*Command).doRun.func1
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:110
   2).  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1
        /Users/apache/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:393
   3).  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End
        /Users/apache/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:432
   4).  github.com/gogf/gf/v2/container/gtype.(*Bool).Val
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/container/gtype/gtype_bool.go:57
   5).  github.com/gogf/gf/v2/os/glog.(*Logger).print
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/glog/glog_logger.go:110
   6).  github.com/gogf/gf/v2/os/glog.(*Logger).printStd
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/glog/glog_logger.go:380
   7).  github.com/gogf/gf/v2/os/glog.(*Logger).Infof
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/glog/glog_logger_api.go:61
   8).  github.com/gogf/gf/v2/net/ghttp.(*Server).Start
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/net/ghttp/ghttp_server.go:131
   9).  github.com/gogf/gf/v2/net/ghttp.(*Server).Run
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/net/ghttp/ghttp_server.go:419
   10). cabinet/internal/cmd.glob..func1
        /Users/apache/GolandProjects/cabinet/internal/cmd/cmd.go:30
   11). github.com/gogf/gf/v2/os/gcmd.(*Command).doRun
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:148
   12). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:81
   13). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:40
   14). github.com/gogf/gf/v2/os/gcmd.(*Command).Run
        /Users/apache/go/pkg/mod/github.com/gogf/gf/v2@v2.1.4/os/gcmd/gcmd_command_run.go:34
   15). main.main
        /Users/apache/GolandProjects/cabinet/main.go:22


Exiting.

```
