### ISSUE TITLE
v2.1.4+版本DB主从库功能失效

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#2251]
```yaml
database:
  default:
  - type: "mysql"
    link: "bbbb:12345678@tcp(192.168.1.1:3306)/test"
    role: "master"
  - type: "mysql"
    link: "aaaa:666666@tcp(192.168.1.2:3306)/test"
    role: "slave"
```
```go
Slave, _ := g.DB().Slave()
glog.Debugf(ctx, "Slave:%v", Slave)
// 即使指定取master还是会取到上次的连接
Master, _ := g.DB().Master()
glog.Debugf(ctx, "Master:%v", Master)
```
```mod
require (
	// github.com/gogf/gf/contrib/drivers/mysql/v2 v2.1.4
	// github.com/gogf/gf/v2 v2.1.4

	github.com/gogf/gf/contrib/drivers/mysql/v2 v2.2.1
	github.com/gogf/gf/v2 v2.2.1
)

```
```shell
go run main.go --gf.debug=1
```

```go
// 关键代码contrib/drivers/sqlite/sqlite_core_test.go
	instanceNameByNode := fmt.Sprintf(
		`%s@%s(%s:%s)/%s`,
		node.User, node.Protocol, node.Host, node.Port, node.Name,
	)
	v := c.links.GetOrSetFuncLock(instanceNameByNode, func() interface{} {
// 由于instanceNameByNode的值一致无法区分主从库连接
```
