### ISSUE TITLE
如何在配置文件中配置server.staticPaths开启静态文件目录映射？

### ISSUE THREAD

**Issue by jckings2007** [gogf/gf#2333]
如题，在https://pkg.go.dev/github.com/gogf/gf/v2/net/ghttp#Server 文档中找到配置项 staticPaths
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/4112790/204484612-94e6b468-6b82-468d-acf9-dc49dbcbb68e.png">
但是staticPaths对应的staticPathItem结构体在文档中没有发现定义，也就不知道应该怎么写这个配置项，尝试了
` staticPaths: [{"/Users/jason/Documents/工作/code/resource":"/resource"}] `
或是  `staticPaths: [{"/resource":"/Users/jason/Documents/工作/code/resource"}] `又或者是`staticPaths:"[["/resource","/Users/jason/Documents/工作/code/resource"]]`等等各种各样的写法均无法生效，请问正确的写法究竟是什么？能否在文档的配置项中带上相应的示例，否则对新入坑的同学来这种猜谜式的编程体验是非常差的

**Comment by hailaz** [comment]
这里有个bug，我稍候修复一下，修复之后用下面这个格式
```yaml
server:
    address: ":8199"
    staticPaths:
      - prefix: ""
        path: ""
```
