### ISSUE TITLE
Problems with configuration `logger.file`

### ISSUE THREAD

**Issue by windvalley** [gogf/gf#2462]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.6 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.3.2

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

vi manifest/config/config.yaml

```yaml
logger:
  path: "logs/" # 日志文件目录, 如果为空, 表示不记录到文件
  file: "{Ymd}.log" # 日志文件格式. 默认为"{Y-m-d}.log"
  level: "all" # DEBU < INFO < NOTI < WARN < ERRO < CRIT, 也支持ALL, DEV, PROD常见部署模式配置名称. level配置项字符串不区分大小写
```
I have changed the log file name to `{Ymd}.log` from default `{Y-m-d}.log`

### 5. What did you expect to see?

When executing `gf run main.go`, it should only generate one file:  `logs/20230220.log`.

### 6. What did you see instead?

It generated two log files: `logs/20230220.log` and `logs/2023-02-20.log`

**Comment by gqcn** [comment]
@windvalley I think you might miss another logger configuration. The `logger` in config.yaml is the configuration for default logger. The `server.logger` is the configuration for logger of http server. Have a check for that?

**Comment by windvalley** [comment]
> @windvalley I think you might miss another logger configuration. The `logger` in config.yaml is the configuration for default logger. The `server.logger` is the configuration for logger of http server. Have a check for that?

@gqcn Thanks for reply. My full configuration about logger is as follows:

```yaml
server:
  # 服务日志(包括访问日志和server错误日志)
  logPath: "logs/"
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"
  # 针对服务日志的扩展配置
  logger:
    ctxKeys: ["user", "mail"]
    rotateExpire: "1d"
    rotateBackupExpire: "30d"
    rotateBackupLimit: 30
    rotateCheckInterval: "1h"

# 开发者通过g.Log()打印的通用日志, 对server服务日志无效
logger:
  path: "logs/"
  file: "{Ymd}.log" # 日志文件格式. 默认为"{Y-m-d}.log"
  level: "all"
  stStatus: 0
  ctxKeys: ["user", "mail"]
  stdout: true
  stdoutColorDisabled: false
  writerColorEnable: false
  rotateExpire: "1d"
  rotateBackupExpire: "30d"
  rotateBackupLimit: 30
  rotateCheckInterval: "1h"

database:
  # sql日志
  logger:
    path: "logs/"
    file: "sql-{Ymd}.log"
    level: "all"
    stdout: true
    ctxKeys: ["user", "mail"]
    rotateExpire: "1d"
    rotateBackupExpire: "30d"
    rotateBackupLimit: 30
    rotateCheckInterval: "1h"
```
I expect to see 4 log files: `20230220.log`, `access-20230220.log`, `error-20230220.log`, `sql-20230220.log`,
but instead to see 5:  `2023-02-20.log`, `20230220.log`, `access-20230220.log`, `error-20230220.log`, `sql-20230220.log`. 
I mean this file `2023-02-20.log` should not be generated. If I have misunderstood something, thank you for correcting me:)

**Comment by gqcn** [comment]
@windvalley Sorry, I could not reproduce this issue in latest version.

**Comment by windvalley** [comment]
> @windvalley Sorry, I could not reproduce this issue in latest version.

I'm sorry, I've missed a condition that produces `20230220.log` after starting the server. 

Add this `g.Log().Debugf(ctx, "use config file: %+v", configFile)` in the entry file `internal/cmd/main.go`, and it will generate 2 log files: `20230220.log` and `2023-02-20.log`.

The relevant logger configuration is as follows:
```yaml
# 开发者通过g.Log()打印的通用日志, 对server服务日志无效
logger:
  path: "logs/"
  file: "{Ymd}.log" # 日志文件格式. 默认为"{Y-m-d}.log"
```
According to this configuration, logically, only file `20230220.log` should be generated.

**Comment by windvalley** [comment]
I have solved this problem I described above by configuring as follows:
```yaml
server:
  # 服务日志(包括访问日志和server错误日志)
  logPath: "logs/"
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"
  # 针对服务日志的扩展配置
  logger:
    # ****** NOTE: ADD THIS ITEM ******
    file: "{Ymd}.log" # 这里只记录server启动过程中gf默认打印的日志, 默认 {Y-m-d}.log; 日志所在路径为server.logPath指定的目录
    ctxKeys: ["user", "mail"]
    rotateExpire: "1d"
    rotateBackupExpire: "30d"
    rotateBackupLimit: 30
    rotateCheckInterval: "1h"

# 开发者通过g.Log()打印的通用日志, 对server服务日志无效
logger:
  path: "logs/"
  file: "{Ymd}.log" # 日志文件格式. 默认为"{Y-m-d}.log"
  level: "all"
  stStatus: 0
  ctxKeys: ["user", "mail"]
  stdout: true
  stdoutColorDisabled: false
  writerColorEnable: false
  rotateExpire: "1d"
  rotateBackupExpire: "30d"
  rotateBackupLimit: 30
  rotateCheckInterval: "1h"

database:
  # sql日志
  logger:
    path: "logs/"
    file: "sql-{Ymd}.log"
    level: "all"
    stdout: true
    ctxKeys: ["user", "mail"]
    rotateExpire: "1d"
    rotateBackupExpire: "30d"
    rotateBackupLimit: 30
    rotateCheckInterval: "1h"
```
