### ISSUE TITLE
Smooth restart does not take effect

### ISSUE THREAD

**Issue by xyqweb** [gogf/gf#2752]
### 1. What version of `Go` and system type/arch are you using?

go1.20.5 linux/amd64

### 2. What version of `GoFrame` are you using?
GoFrame  v2.4.4

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?
config.yaml
```yaml
server:
  address:     ":8080"
  dumpRouterMap:       false
  accessLogEnabled:    true
  errorLogEnabled:    true
  accessLogPattern:    "access.log"
  errorLogPattern:    "error.log"
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"
  graceful: true
  gracefulTimeout: 10
  gracefulShutdownTimeout: 10

```

```go

g.Wait()//not support os signal
```

#### try `GoFrame` version : 2.4.4 and 2.3.3
```shell
kill -SIGUSR1 PID

```

### 6. What did you see instead?

`GoFrame` 2.4.4  No response and no overload

`GoFrame` 2.3.3 response: 
2023-07-08 11:53:54.741 11285: server gracefully shutting down by api
2023-07-08 11:53:54.744 [INFO] pid[11285]: all servers shutdown

@gqcn
