### ISSUE TITLE
Redis `maxConnLifetime` parameter not working

### ISSUE THREAD

**Issue by windvalley** [gogf/gf#2775]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.20.4 darwin/amd64`

### 2. What version of `GoFrame` are you using?

```
GoFrame CLI Tool v2.5.0, https://goframe.org
GoFrame Version: v2.5.0 in current go.mod
CLI Installed At: /Users/xg/go/bin/gf
CLI Built Detail:
  Go Version:  go1.20.4
  GF Version:  v2.5.0
  Git Commit:  2023-07-17 10:06:06 41c0dde9bf12550ad2f1cc77def20ea233d25fef
  Build Time:  2023-07-17 10:09:33
```

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

vi manifest/config/config.yaml
```yaml
redis:
  # 默认分组, 调用方式: g.Redis()
  default:
    address: 127.0.0.1:6379
    # 数据库索引, 0-15
    db: 0
    # 访问授权密码
    pass:
    # 连接最长存活时间, 默认值: 30s;
    # 多个redis请求会复用一个连接,
    # 从建立连接开始计算, 只要超过这个时间就会自动断开连接,
    # 就算此时有redis请求也会先关闭当前连接, 然后重新建一个新的连接,
    # 除非请求是一个阻塞式请求, 比如: BLPop等, 此时连接将始终保持,
    # 直到从队列读取到数据才会断开并自动重建连接.
    maxConnLifetime: 30s
    # 连接最大空闲时间, 默认值: 10s;
    # 只要连接空闲超过idleTimeout后, 就会断开连接, 不会考虑maxConnLifetime的时间.
    idleTimeout: 5m   # 此处设置成5m, 方便测试maxConnLifetime的效果, 实际使用中应小于maxConnLifetime才有意义.
```

遇到的问题是: 如果将参数`maxConnLifetime`设置成小于1分钟(比如默认值: 30s), 访问redis建立连接后(首次建立连接后保持空闲状态), 通过命令行持续观察tcp连接, 发现是1分钟后才断开连接.

命令行(测试平台MacOS): ` while :;do echo ++++++++++++++++; date +%F-%T; netstat -nat |fgrep \.6379;sleep 10;done`

### 5. What did you expect to see?

按照参数`maxConnLifetime`配置的时间断开连接.

### 6. What did you see instead?

将参数`maxConnLifetime`设置成小于1分钟, 还是1分钟断连.
