### ISSUE TITLE
v2.4.2 g.log.info log cannot be written to the file

### ISSUE THREAD

**Issue by walingcc** [gogf/gf#2867]
```
server:
  address:     ":8200"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  sessionPath: "storage/gsessions"
    # 日志基本配置
  logPath: "logs"                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout: true               # 日志是否输出到终端。默认为true
  errorStack: true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
  errorLogEnabled: true               # 是否记录异常日志信息到日志中。默认为true
  errorLogPattern: "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled: true              # 是否记录访问日志。默认为false
  accessLogPattern: "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
  logger:
    level: "all"
    stdout: true
    path: "./logs"          # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file: "{Y-m-d}.log"          # 日志文件格式。默认为"{Y-m-d}.log"
    rotateSize: "100M"           # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupLimit: 10
    rotateBackupExpire: "60d"
    rotateBackupCompress: 9       # 日志文件压缩级别，0-9,9最高
    rotateCheckInterval: "24h"
```
goframe v2.4.2版本，使用g.log.info日志无法写到文件，只有控制台输出；请问下，是哪里配置的问题吗
