### ISSUE TITLE
[🐞BUG]DAO,Configuration file parsing error

### ISSUE THREAD

**Issue by Tiper-In-Github** [gogf/gf#2944]
### 1. What version of `Go` and system type/arch are you using?
>go version
go version go1.20 windows/amd64

### 2. What version of `GoFrame` are you using?
>gf version
GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.2 in current go.mod

### 3. Can this issue be re-produced with the latest release?
是的(Yes)

### 4. What did you do?
我使用'gf gen dao'为我生成dao代码，在config.yaml中，我分别配置了default和prod两个不同的数据库(I used 'gf gen dao' to generate dao code for me. In config.yaml, I configured two different databases: default and prod)：
```yaml
# database.
database:
  default:
    link:  "mysql:name:password@tcp(本地开发mysql地址)/xxxxx?loc=Local"
  prod:
    link: "mysql:name:password@tcp(生产环境mysql地址)/xxxxx?loc=Local"
```
之后我将hack下的config.yaml配置为使用prod并且执行‘gf gen dao’，查看生成的代码是正常的，并且完美的运行了。
但当我关闭生产环境的数据库后，尝试修改为使用default配置，执行‘gf gen dao’，查看代码正常，但我程序异常，无法连接数据库，经过查看和对比，gf依然在使用prod的连接地址。
(Afterwards, I configured config.yaml under hack to use prod and executed 'gf gen dao' to check that the generated code was normal and running perfectly.
But when I closed the database in the production environment, I tried to modify it to use the default configuration and execute 'gf gen dao'. The code was normal, but my program was abnormal and I was unable to connect to the database. After checking and comparing, GF still used the connection address of prod.)
- ps:当我将database.prod注释后，程序正常工作了，gf使用了正确的配置来连接数据库(After commenting on database.prod, the program worked properly and GF used the correct configuration to connect to the database)

### 5. What did you expect to see?
更改后，gf应该使用database.default.link作为数据库连接地址
After the change, GF should use database.default.link as the database connection address

### 6. What did you see instead?
更改后，gf依然使用database.prod.link作为数据库连接地址
After the change, GF still uses database.prod.link as the database connection address

### 7.Code
```yaml
# database.
database:
  default:
    link:  "mysql:name:password@tcp(本地开发mysql地址)/xxxxx?loc=Local"
  prod:
    link: "mysql:name:password@tcp(生产环境mysql地址)/xxxxx?loc=Local"
```

无需示例代码，参考上面提供的格式设置config.yaml，然后hack修改为使用default组，执行 'gf gen dao'，可观察到代码正常但运行时依然使用database.prod.link作为数据库连接地址
No sample code is required. Please refer to the format provided above to set config.yaml, and then modify the hack to use the default group and execute 'gf gen dao'. It can be observed that the code is normal but still uses database.prod.link as the database connection address during runtime
