### ISSUE TITLE
When connect local jaeger, how to do config ?

### ISSUE THREAD

**Issue by kuchaguangjie** [gogf/gf#3131]
```
// trace multiple within a process,
func tracingWithinProcess() {
	const (
		serviceName = "gf-learn"
		endpoint    = "localhost:4318" // TODO: what to fill ?
		path        = "/v1/traces"     // TODO: what to fill ?
	)

	var ctx = gctx.New()
	tp, err := otlphttp.Init(serviceName, endpoint, path)
	if err != nil {
		g.Log().Fatal(ctx, err)
	}
	defer tp.Shutdown(ctx)

	ctx, span := gtrace.NewSpan(ctx, "main")
	defer span.End()
}
```
When run, get error:
> 2023/11/05 13:09:35 traces export: Post "http://localhost:4318/v1/traces": read tcp 127.0.0.1:42386->127.0.0.1:4318: read: connection reset by peer

I've started the jaeger locally via docker-compose:
```
version: '3.8'
services:
    all-in-one:
        container_name: jaeger
        environment:
            - 'COLLECTOR_ZIPKIN_HOST_PORT=:9411'
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - '6831:6831/udp'
            - '6832:6832/udp'
            - '5778:5778'
            - '16686:16686'
            - '4317:4317'
            - '4318:4318'
            - '14250:14250'
            - '14268:14268'
            - '14269:14269'
            - '9411:9411'
        image: 'jaegertracing/all-in-one:latest'
```
