### ISSUE TITLE
[BUG] Schema Configuration for postgresql did not work

### ISSUE THREAD

**Issue by AlphaFoxz** [gogf/gf#3202]
### 1. What version of `Go` and system type/arch are you using?
go1.21.5 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.5.7

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
- 在配置文件里做了如下配置 Configuration in `hack/config.yaml` like this
```yaml
gfcli:
  gen:
    dao:
      - link: "pgsql:user=postgres password=123456host=127.0.0.1 port=5432 dbname=postgres search_path=app"
        namespace: "app"
```
- 然后执行代码生成命令 Then execute `gf gen dao`

### 5. What did you expect to see?
应该能正确生成代码
The command gen Dao code Correctly

### 6. What did you see instead?
- 当连接至postgresql的时候，只要配置了link，schema就永远不生效
- The config for schema will never work when db is postgresql and configuration contains `link`.
- 命令的查询sql总是会查找`n.nspname = 'public'`。查询语句如下
- Generation sql will always select for `n.nspname = 'public'`. Like this
```sql
SELECT c.relname FROM pg_class c INNER JOIN pg_namespace n ON c.relnamespace = n.oid WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND c.relpartbound IS NULL ORDER BY c.relname
```
- `search_path`是个官方的url参数，但是它在本项目中没有任何作用，link是本项目api中的必填项，但是一旦填了link就会导致`namespace`配置失效。这很混乱
- `search_path` is an official url parameter, but it has no effect in this project. `link` is a required config in the API of this project, but once the link is filled in, the `namespace` configuration will become invalid. this is confusing
- 我是个初学者，刚开始用就被这个问题卡住了，我也不太清楚database的link是否有同样的问题
- i am a beginner and i dont know if the same thing happend with `database.default.link`
