### ISSUE TITLE
gf2.0.0版本gparser解析yaml文件报错json: unsupported type: map[interface {}]interface {}

### ISSUE THREAD

**Issue by praynise** [gogf/gf#336]
代码：
```
package main

import (
	"fmt"
	"github.com/gogf/gf"
	"github.com/gogf/gf/encoding/gparser"
	_ "github.com/lib/pq"
	"gopkg.in/yaml.v3"
	"os"
)

type Conf struct {
	Broker    Broker
	Database  Database
	Scheduler Scheduler
	Worker    Worker
	Common    Common
	Report    Report
}

type Broker struct {
	Ip        string
	Tcport    string
	Httpport  string
	User      string
	Pwd       string
	Clusterid string
}

type Database struct {
	Ip     string
	Port   string
	User   string
	Pwd    string
	Dbname string
}

type Scheduler struct {
	SleepTime   int
	Pidfilepath string
	A2rparallel int
}

type Worker struct {
	Name        string
	Domains     map[string]interface{}
	Temppath    string
	Pidfilepath string
}

type Common struct {
	Filepath string
	Logpath  string
	Logdebug bool
	Logtrace bool
}

type Report struct {
	Localip   string
	Localport string //暂不启用
}

func main() {

	fmt.Println("gf读取yaml文件")
	fmt.Println(gf.VERSION)
	_,err := gparser.Load("config.yaml")
	if err != nil{
		fmt.Println("oops,read config.yaml err:",err)
	}


	fmt.Println("yaml.v3读取yaml文件")
	f,err := os.Open("config.yaml")
	if err != nil{
		panic(err)
	}
	var conf Conf
	err = yaml.NewDecoder(f).Decode(&conf)
	if err != nil{
		panic(err)
	}
	fmt.Println(conf)
}
```

输出：
```
gf读取yaml文件
v2.0.0
oops,read config.yaml err: json: unsupported type: map[interface {}]interface {}
yaml.v3读取yaml文件
{{127.0.0.1  8222 alfxnats alfxnats alfxnats} {110.1.1.227 27017 alfxdev alfxdev alfxdev} {300  4} {worker1 map[free:3 officenet:3 producnet:3] /home/alfx/proc } {/home/alfx/file home/alfx/log true true} {127.0.0.1 }}
```

**Comment by praynise** [comment]
yaml文件内容如下：
```
broker:
  ip: "127.0.0.1"
  tcpport: "4222"
  httpport: "8222"
  user: "alfxnats"
  pwd: "alfxnats"
  clusterid: "alfxnats"
database:
  ip: "110.1.1.227"
  port: "27017"
  user: "alfxdev"
  pwd: "alfxdev"
  dbname: "alfxdev"
scheduler:
  a2rparallel: 4
  sleeptime: 300
worker:
  name: "worker1"
  domains:
    officenet: 3
    producnet: 3
    free: 3
  temppath: "/home/alfx/proc"
common:
  filepath: "/home/alfx/file"
  logpath: "home/alfx/log"
  logdebug: true
  logtrace: true
report:
  localip: "127.0.0.1"
  localport: ""
```
