### ISSUE TITLE
gjson,与yaml互转数字类型 变字符类型

### ISSUE THREAD

**Issue by jetlwx** [gogf/gf#360]
### 1. What version of `Go` and system type/arch are you using?

go version go1.12.7 linux/amd64

### 2. What version of `GoFrame` are you using?

1.9.4

### 4. What did you do?

```go
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/gogf/gf/util/gconv"

	"github.com/gogf/gf/encoding/gjson"

	"github.com/gogf/gf/encoding/gyaml"
)

func main() {
	file, err := ioutil.ReadFile("/data/go/gopath/src/github.com/jetlwx/src/coamp/k8s/yaml/useing/http-daemon/http-daemon-svc.yaml")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("file=", gconv.String(file))

	a, _ := gyaml.ToJson(file)
	fmt.Println(string(a))

	js, _ := gjson.DecodeToJson(a)
	jyaml, _ := js.ToYamlString()
	fmt.Println(jyaml)
}
```

```
//--------- 输出如下
file= apiVersion: v1
kind: Service
metadata:
  labels:
    name: http-daemon
  name: http-daemon
  namespace: default
spec:
  ports:
  - name: http-daemon
    port: 8080 //**这里是int类型**
    protocol: TCP
    targetPort: 9212 //**这里是int类型**
  selector:
    app: http-daemon
    version: v0930-082326

{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"name":"http-daemon"},"name":"http-daemon","namespace":"default"},"spec":{"ports":[{"name":"http-daemon","port":8080,"protocol":"TCP","targetPort":9212}],"selector":{"app":"http-daemon","version":"v0930-082326"}}}
apiVersion: v1
kind: Service
metadata:
    labels:
        name: http-daemon
    name: http-daemon
    namespace: default
spec:
    ports:
      - name: http-daemon
        port: "8080"  //**变字符类型**
        protocol: TCP
        targetPort: "9212"  //**变字符类型**
    selector:
        app: http-daemon
        version: v0930-082326
```
