### ISSUE TITLE
cli: Use the gf gen dao command to generate sqlite entities, and the results are all empty structures.

### ISSUE THREAD

**Issue by lingcoder** [gogf/gf#3706]
### Go version

go version go1.22.4 windows/amd64

### GoFrame version

2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

切换到项目app/demo/文件夹下，执行：gf gen dao

hack配置如下
```
gfcli:
    gen:
    dao:
      - link: "sqlite:./mydb.db?cache=shared&mode=rwc"
        tables: "table_demo"
        descriptionTag: true
        noModelComment: true
        overwriteDao: true
        importPrefix: "demo-project/app/demo/internal"
        stdTime: true
        typeMapping:
          decimal:
            type:   decimal.Decimal
            import: github.com/shopspring/decimal
```
### What did you see happen?

![7fa732ab33b44f440645c1263fcc316](https://github.com/user-attachments/assets/032943b7-8be3-4d3a-9e96-268d150c8a4b)

### What did you expect to see?

生成正常的实体结构体
