### ISSUE TITLE
g.log: format Excessive prefix(前缀多余)

### ISSUE THREAD

**Issue by wordgao** [gogf/gf#3720]
### Go version

go version go1.22.5 linux/amd64

### GoFrame version

2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```
logger:
  path: "./logs"
  level: "all"
  stdout: true
  file: "{Y-m-d}.log"
  timeFormat: "2006-01-02 15:04:05"
```
g.Log().Info(ctx,log...)
2024-08-05T01:52:25.193000486Z 2024-08-05 09:52:25 [INFO]xxxxxxxx......

(default)+config(format)+[INFO]+log
After configuration, prefix repetition time。

### What did you see happen?

```
logger:
  path: "./logs"
  level: "all"
  stdout: true
  file: "{Y-m-d}.log"
  timeFormat: "2006-01-02 15:04:05"
```
g.Log().Info(ctx,log...)
~~2024-08-05T01:52:25.193000486Z~~ 2024-08-05 09:52:25 [INFO]xxxxxxxx......
config(format)+[INFO]+log

### What did you expect to see?

```
logger:
  path: "./logs"
  level: "all"
  stdout: true
  file: "{Y-m-d}.log"
  timeFormat: "2006-01-02 15:04:05"
```
g.Log().Info(ctx,log...)
~~2024-08-05T01:52:25.193000486Z~~ 2024-08-05 09:52:25 [INFO]xxxxxxxx......
config(format)+[INFO]+log
