### ISSUE TITLE
The field names generated by "gf gen dao" have changed. v2.7.2

### ISSUE THREAD

**Issue by livecopilot** [gogf/gf#3749]
### Go version

go1.22.5 darwin/arm64

### GoFrame version

2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

gf gen dao

### What did you see happen?

![40ADD79542EC5DECAE42E5C79F066BD4](https://github.com/user-attachments/assets/2e91e6dd-143e-45a1-8a04-beff41c65b6b)

### What did you expect to see?

in gf v2.7.1 and other old version , it's ParentId, and I don't want make it change in v2.7.2。

**Comment by oldme-git** [comment]
v2.7.3 can't reproduce the issue. Please you try new version or provide more information. Thanks!

**Comment by livecopilot** [comment]
> v2.7.3 can't reproduce the issue. Please you try usring new version or provide more information. Thanks!

v2.7.3 has the same issue.
and i use pgsql, version v14

hack/config.yaml like 
```yaml
gfcli:
  # 工具编译配置
  build:
    arch: "amd64"
    system: "linux"
    path: "./temp"
    packSrc: ""
    extra: '-tags timetzdata -ldflags="-s -w"'
    mod: ""
    cgo: 0

  # dao生成
  gen:
    dao:
      - link: "pgsql:[account]:[password]@tcp([host]:5432)/[database]"
        removePrefix: ""
        descriptionTag: true
        noModelComment: true
        daoPath: "repository/db/dao"
        doPath: "repository/db/do"
        entityPath: "repository/db/entity"
```
