### ISSUE TITLE
关于goframe连接阿里云的rds数据库

### ISSUE THREAD

**Issue by 0ytian** [gogf/gf#386]
我想问一下，goframe是还不支持阿里云rds数据库吗？还是我的用法有问题？我用gorm连接阿里云数据库是没有问题的。
数据库配置如下：
```toml
[database]
    [[database.test]]
        type = "mysql"
        link = "test:test@tcp(test.mysql.rds.aliyuncs.com:3306)/test"
```

代码如下：
```golang
var (
	m = g.DB("test").Table("test")
)

func GetList(where ...interface{}) (gdb.Result, error) {
	return m.Where(where).All()
}
```

运行错误：
```shell
runtime: VirtualAlloc of 3012476928 bytes failed with errno=1455
fatal error: out of memory
```
