### ISSUE TITLE
os/gtime: sharding db && sharding table

### ISSUE THREAD

**Issue by okami-chen** [gogf/gf#4212]
### What do you want to ask?

How to set up in the YAML configuration file of the framework, and ensure that GF Gen DAO only generates one DAO file instead of generating many DAO files for user_xxx

**Comment by okami-chen** [comment]
like this?
```
gendao:
  - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    shardingPattern:
      - "user_?"
```
