### ISSUE TITLE
os/gtime: Error: Error 20024 (44000): Sharding value '[B@3ead1ae5' must implements Comparable.

### ISSUE THREAD

**Issue by okami-chen** [gogf/gf#4303]
### Go version

1.24.4

### GoFrame version

2.9.0

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

sql语句没有问题，在其他客户端可以正常执行，现在查询、写入、更新都不行。
```
			service.Inventory().ShardingSphere(ctx).
				Where("created_at >= ?", "2025-05-01 00:00:00").
				Where("created_at < ?", "2025-06-01 00:00:00").
				Where("id = ?", id).Scan(&inventoryObj)
```

### What did you see happen?

使用了apache shardingSphere做的分表

```
rules:
  - !SHARDING
    tables:
      inventory:
        actualDataNodes: ms-wms.inventory_${2024..2030}${(1..12).collect{ t -> t.toString().padLeft(2, '0') }}
        tableStrategy:
          standard:
            shardingColumn: created_at
            shardingAlgorithmName: t_inventory_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

      inventory_log:
        actualDataNodes: ms-wms.inventory_log_${0..15}
        tableStrategy:
          standard:
            shardingColumn: product_id
            shardingAlgorithmName: t_inventory_log_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

    shardingAlgorithms:
      t_inventory_inline:
        type: INTERVAL
        props:
          datetime-pattern: "yyyy-MM-dd HH:mm:ss"
          datetime-lower: "2024-01-01 00:00:00"
          sharding-suffix-pattern: "yyyyMM"
          datetime-interval-amount: 1
          datetime-interval-unit: MONTHS

      t_inventory_log_inline:
        type: INLINE
        props:
          algorithm-expression: inventory_log_${product_id % 16}

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 1
```

### What did you expect to see?

```
2025-06-10T17:02:10.084+08:00 [ERRO] {b8e88c8fefa24718a9a4173e37d811a8} /Users/mac/wwwroot/go-service/ms-wms/internal/cmd/sharding.go:23: [ 38 ms] [sharding] [wms] [rows:0  ] SELECT `id`,`warehouse_id`,`product_id`,`batch_no`,`cost_price`,`total_qty`,`locked_qty`,`frozen_qty`,`created_at`,`updated_at`,`deleted_at` FROM `inventory` WHERE ((created_at >= '2025-05-01 00:00:00') AND (created_at < '2025-06-01 00:00:00') AND (id = 18353323766)) AND `deleted_at` IS NULL LIMIT 1
Error: Error 20024 (44000): Sharding value '[B@3ead1ae5' must implements Comparable. 

```

**Comment by okami-chen** [comment]
不使用限制条件`created_at`正常

**Comment by lingcoder** [comment]
经排查，这个报错来自 ShardingSphere-Proxy，与 GoFrame 无关。

**原因**：gf 通过预处理语句（`COM_STMT_PREPARE` / `COM_STMT_EXECUTE`）执行查询，`go-sql-driver/mysql` 在二进制协议中把 Go 的 `string` 参数标记为 `MYSQL_TYPE_STRING`(0xfe)，而 JDBC 客户端用的是 `MYSQL_TYPE_VAR_STRING`(0xfd)。ShardingSphere-Proxy 把 0xfe 与各类 BLOB 归为一组（`MySQLBinaryProtocolValueFactory` → `MySQLByteLenencBinaryProtocolValue`），读成 `byte[]`；`byte[]` 没有实现 `Comparable`，INTERVAL 分片算法拿它和 `datetime-lower` 比较时就抛出 `Sharding value '[B@3ead1ae5' must implements Comparable.`。这也解释了你说的「不使用限制条件 `created_at` 正常」——只有作为分片键的字符串条件会走到这段比较逻辑。

同样的问题在 GORM 下也能复现，并非 gf 特有：

- apache/shardingsphere#37993
- apache/shardingsphere#38381

上游已在 apache/shardingsphere#38382 修复（2026-03-09 合入 master）。该修复目前**尚未包含在任何已发布版本**中（最新发布版为 5.5.3 / 2026-02-28），需等待 5.5.4。

在此之前，可以在数据库配置中加上 `interpolateParams=true`，让驱动在客户端把参数插值成完整 SQL 文本（走 `COM_QUERY`），不再使用二进制预处理协议，即可绕过：

```yaml
database:
  default:
    link:  "mysql:user:pass@tcp(127.0.0.1:3307)/ms-wms"
    extra: "interpolateParams=true"
```

也可以直接写在 `link` 里：

```yaml
database:
  default:
    link: "mysql:user:pass@tcp(127.0.0.1:3307)/ms-wms?interpolateParams=true"
```

注意 `interpolateParams` 不能与 BIG5 / CP932 / GB2312 / GBK / SJIS 等多字节字符集同时使用（gf 默认 charset 为 `utf8`，不受影响）。

据此关闭本 issue。如果你认为这仍是 gf 侧的问题，欢迎补充信息后重开。
