### ISSUE TITLE
[建议] gf-cli 提供可以处理编译结果的选项

### ISSUE THREAD

**Issue by loocor** [gogf/gf#656]
### 目的

可以把编译结果按配置自动处理，比如压缩、上传等，提升开发、部署效率。

### 表现形式举例

在如下的配置里，
```toml
[compiler]
    name     = "my-app"
    version  = "1.0.0"
    arch     = "386,amd64"
    system   = "linux,windows,darwin"
    output   = ""
    path     = "./bin"
    extra    = "-ldflags \"-s -w\""
```

增加一个类似这样的选项，其中 `$$RESULT` 是编译结果对象：

```toml
    handler = "upx -9 $$RESULT"
```

这个 `handler` 参数不仅可以用 `upx` 来压缩编译结果，还可以这样来用：

```toml
    handler = "scp $$RESULT username@ipaddress:folder "
```

通过 `scp` 把编译结果传到指定的服务器上去。

理论上，接受任何可用的 shell 命令，对编译结果进行操作。
