### ISSUE TITLE
大文件下载出现断流、没有网速的情况

### ISSUE THREAD

**Issue by ztcjn** [gogf/gf#661]
### 标准包net/http 正常

```toml
# HTTP Server
[server]
	Address     = ":8800"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "./log/gf-app/server"
```

直接使用默认配置：

```go
func main() {
	s := g.Server()
	s.SetIndexFolder(true)
	s.Run()
}
```

另外：还测试过局域网 下载100MB的文件 也出现相同情况 

用的是阿里云服务器的内网
