### ISSUE TITLE
Add internal variable parsing support for package gcfg

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#683]
There might be  some duplicate configuration items in the configuration file, or multiple configuration items need to share a certain configuration. We can refer to them through internal variables instead of repeated definitions.

For example:
```toml
[logger]
    Path = "/var/log/app"

[server]
    LogPath = "/var/log/app/server"
```
we can improve it as:
```toml
[logger]
    Path = "/var/log/app"

[server]
    LogPath = "{{logger.Path}}/server"
```
