### ISSUE TITLE
日志滚动同时使用按日志大小和时间切分时时间配置项未生效

### ISSUE THREAD

**Issue by GuardAngelY** [gogf/gf#705]
gf版本: v1.13.0
问题描述:
日志滚动同时配置按大小和按时间切分时, 只有按大小切分有生效

配置如下

    RotateSize           = "50M"
    RotateExpire         = "1d"
    RotateBackupLimit    = 999
    RotateBackupExpire   = "30d"
    RotateBackupCompress = 9

产生的最终日志文件类似
- 2020-06-01.20200601014235845942.log.gz
- 2020-06-01.20200601062021172464.log.gz
- 2020-06-01.log

在经过几天时间后, 2020-06-01.log已满足RotateExpire配置的一天未进行修改则进行压缩的条件, 但未被处理

**Comment by gqcn** [comment]
待确认

**Comment by csrgxtu** [comment]
expire 和 rotate 功能都没有生效
```toml
    [logger.data_logger]
        RotateSize           = "1024M"
        RotateBackupLimit    = 2
        RotateBackupExpire   = "1d"
        Path = "/tmp/log/LogVerify"
        Level = "NOTI"
        Stdout = false
```
![image](https://user-images.githubusercontent.com/5053620/86524269-0e7d5000-beab-11ea-86a5-f120b9eaf5ff.png)
