### ISSUE TITLE
关于日志滚动切分

### ISSUE THREAD

**Issue by chenall** [gogf/gf#832]
go version go1.14.5 windows/amd64
gf v1.13.3-0.20200725070508-e252d8b740a8

根据 https://goframe.org/os/glog/rotate 说明文档进行了如下配置

```toml
    RotateExpire         = "1d"
    RotateBackupLimit    = 3
    RotateBackupExpire   = "2d"
    RotateBackupCompress = 5
```

发现没有生效.

调试了一下发现logger配置的RotateExpire和RotateBackupExpire都是0. 

然后参考 time.ParseDuration 的用法
```go
// ParseDuration parses a duration string.
// A duration string is a possibly signed sequence of
// decimal numbers, each with optional fraction and a unit suffix,
// such as "300ms", "-1.5h" or "2h45m".
// Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
```
修改成了如下配置就可以了.
```toml
    RotateExpire         = "24h"
    RotateBackupLimit    = 3
    RotateBackupExpire   = "48h"
    RotateBackupCompress = 5
```
