### ISSUE TITLE
能否提供orm连接超时时间设置

### ISSUE THREAD

**Issue by siyue8899** [gogf/gf#868]
gf 的 orm 配置没有发现能配置的地方, 但是所用的驱动包 `github.com/go-sql-driver/mysql` 里面有配置  下面那个 timeout
`user:password@tcp([de:ad:be:ef::ca:fe]:80)/dbname?timeout=90s&collation=utf8mb4_unicode_ci`

gf 封装的则是,没有使用到 **timeout** 连接超时配置
```golang
// Open creates and returns a underlying sql.DB object for mysql.
func (d *DriverMysql) Open(config *ConfigNode) (*sql.DB, error) {
	var source string
	if config.LinkInfo != "" {
		source = config.LinkInfo
		// Custom changing the schema in runtime.
		if config.Name != "" {
			source, _ = gregex.ReplaceString(`/([\w\.\-]+)+`, "/"+config.Name, source)
		}
	} else {
		source = fmt.Sprintf(
			"%s:%s@tcp(%s:%s)/%s?charset=%s&multiStatements=true&parseTime=true&loc=Local",
			config.User, config.Pass, config.Host, config.Port, config.Name, config.Charset,
		)
	}
	intlog.Printf("Open: %s", source)
	if db, err := sql.Open("mysql", source); err == nil {
		return db, nil
	} else {
		return nil, err
	}
}
```

**Comment by gqcn** [comment]
@siyue8899 你当然可以使用`database`配置项中的`link`或者`linkinfo`来配置，例如：
```toml
[database]
    link="user:password@tcp([de:ad:be:ef::ca:fe]:80)/dbname?timeout=90s&collation=utf8mb4_unicode_ci"
```
