### ISSUE TITLE
g.DB问题，config.toml 设置了maxLifetime和maxOpen，无效

### ISSUE THREAD

**Issue by 804657038** [gogf/gf#899]
```toml
[database]
    [[database.default]]
       host         = "127.0.0.1"
       port         = "3306"
       user         = "smile"
       pass         = "fuckyoucn"
       name         = "smile.action"
       type         = "mysql"
       role         = "master"
       debug        = "false"
       charset      = "utf8"
       maxOpen       = "300"
       maxLifetime   = "30"
```
